spring:
  application:
    name: zuul-demo
server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    prefer-ip-address: true  # 采用ip注册
    #  定义实例ID格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

#使用Zuul构建微服务网关
zuul:
  IpFilter:    #过滤器禁用-IpFilter的pre类型的过滤器禁用
    pre:
      disable: true
  #路由前缀
#  prefix: /rest
  host:
    connect-timeout-millis: 150000 #HTTP连接超时大于Hystrix的超时时间
    socket-timeout-millis: 60000  #socket超时
  routes:
    #指定具体服务路由--访问规则是“API 网关地址+访问的服务名称+接口 URI”
    provider:
      path: /api-provider/**

    biancheng-a:
      path: /spring-boot-first/**
#      url: http://c.biancheng.net
      url: http://localhost:9091/
    #本地跳转
    fsh-substitution:
      path: /api-local/**
      url: forward:/local

ribbon:        #设置ribbon的超时时间小于zuul的超时时间
  ReadTimeout: 10000
  ConnectTimeout: 10000

