spring:
  application:
    name: spring-boot-admin-client-one
#  boot:
#    admin:
#      client:
#        url: http://localhost:30000
#        username: admin
#        password: admin
server:
  port: 31000

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true  # 采用ip注册
    #  定义实例ID格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

# spring-boot-starter-actuator
management:
  endpoints:
    web:
      exposure:
        # 默认info|health yml配置必须加''
        include: '*'
logging:
  file:
    name: log/spring-boot-admin-client-one.log
