spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: zhang
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
#    druid:
#      max-active: 20
#      min-idle: 8
#      initial-size: 10
