spring:
  application:
    name: sleuth-provider
#  zipkin:
#    base-url: http://127.0.0.1:9411
server:
  port: 18081
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    prefer-ip-address: true  # 采用ip注册
    #  定义实例ID格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    # 元数据使用
    metadata-map:
      yuantiandi: yinjihuan
# spring-boot-starter-actuator
management:
  endpoints:
    web:
      exposure:
        # 默认info|health yml配置必须加''
        include:  '*'


