spring:
  application:
    name: spring-boot-admin-server
  security:
    user:
      name: admin
      password: admin
  # 增加邮件服务器
#  mail:
#    host: smtp.qq.com
#    username: 154704230@qq.com
#    # https://tool.oschina.net/encrypt
#    # U2FsdGVkX1/lYnTbCNc92pBWenRCzNY6aRBRHxxnB9mfS6E0ivii0j98HlzjMjFt
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#  boot:
#    admin:
#      notify:
#        mail:
#          to: f154704230@163.com
#          from: 154704230@qq.com

server:
  port: 30000

eureka:
  client:
    register-with-eureka: false  #由于该应用为注册中心，所以设置为false,代表不详注册中心注册自己
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true  # 采用ip注册
    #  定义实例ID格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        # 默认info|health yml配置必须加''
        include:  '*'